# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Nate Graham <nate@kde.org

# 3rd-party Apps that require low-level access so we can't get them from
# Flathub. Other apps are built by us in packages-kde.conf, or come from
# from Flathub.

[Content]
Packages=
    gammaray # GUI debugging for Qt apps
    orca # screen reader

