#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2026 Harald Sitter <sitter@kde.org>

set -eu

MARKER="/tmp/kde-linux-os-release-generator.marker"

if [ "$SYSTEMD_IN_INITRD" = "1" ] && [ ! -e "$MARKER" ]; then
    . /usr/lib/os-release
    printf "Image ID: %s; Image Version: %s" "$IMAGE_ID" "$IMAGE_VERSION" \
        | systemd-cat --identifier=kde-linux --priority=info
    touch "$MARKER"
fi
