#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2025-2026 Vishal Rao <vishalrao@gmail.com>

build() {
    map add_binary \
        /usr/lib/libblkid.so \
        /usr/lib/libmount.so
}
