# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
# SPDX-FileCopyrightText: 2025 Thomas Duckworth <tduck@filotimoproject.org>

# This sets the memory lock limit for the users logged in via PAM,
# more specifically, users logged in on via SSH or tty (console).
# Limits related to terminals in graphical sessions depend on a
# change in /usr/lib/systemd/user.conf.d or system.conf.d config files.
# This does not affect the memory lock limit of system services.

# Increase the maximum locked memory limit to allow apps which may require this
# to lock more memory, such as digital audio workstations.
* soft memlock 2147484
* hard memlock 2147484
